### ISSUE TITLE
whitepaper's "source code" section appears to be wrong

### ISSUE THREAD

**Issue by dkg** [PeerioTechnologies/peerio#2]
https://s3.amazonaws.com/peerio-static-assets/whitepaper.pdf

has a "source code" section (page 22) that says:

> The Peerio client library source code can be reviewed on Github under https://github.com/PeerioTechnologies/peerio-icebear.
> The desktop (Mac, Windows, Linux) client codebase is also available at https://github.com/PeerioTechnologies/peerio-icebear
> The mobile (Android, iOS) client codebase is available at https://github.com/PeerioTechnologies/peerio-icebear

The last two links seem to be incorrect, according to the project cards visible at https://github.com/PeerioTechnologies

**Comment by flohdot** [comment]
Indeed, @dkg. Thanks a lot for reporting; we'll have it fixed in a bit. Desktop should point to https://github.com/PeerioTechnologies/peerio-desktop and Mobile to https://github.com/PeerioTechnologies/peerio-mobile

**Comment by flohdot** [comment]
Fixed!
