### ISSUE TITLE
Linux server building?

### ISSUE THREAD

**Issue by gkua** [PeerioTechnologies/peerio#3]
Hi, followed your building documentation but got lost to errors
`npm ERR! peerio-2@2.107.0 compile: `run-s -ln cleanup icebear-copy && run-p -ln compile:* static:copy react-toolbox`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peerio-2@2.107.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-22T19_53_24_921Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peerio-2@2.107.0 internal-build-linux: `NODE_ENV=production npm run compile && NODE_ENV=production build --linux --x64 --publish never`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peerio-2@2.107.0 internal-build-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-22T19_53_24_941Z-debug.log
root@ubuntu-s-1vcpu-2gb-lon1-01:~/peerio-desktop-2.107.0# clear
root@ubuntu-s-1vcpu-2gb-lon1-01:~/peerio-desktop-2.107.0# npm run internal-build-linux

> peerio-2@2.107.0 internal-build-linux /root/peerio-desktop-2.107.0
> NODE_ENV=production npm run compile && NODE_ENV=production build --linux --x64 --publish never

> peerio-2@2.107.0 compile /root/peerio-desktop-2.107.0
> run-s -ln cleanup icebear-copy && run-p -ln compile:* static:copy react-toolbox

[cleanup     ]
[cleanup     ] > peerio-2@2.107.0 cleanup /root/peerio-desktop-2.107.0/package.json
[cleanup     ] > rm -rf app/build && mkdirp app/build
[cleanup     ]
[cleanup     ]
[cleanup     ] > peerio-2@2.107.0 cleanup /root/peerio-desktop-2.107.0
[cleanup     ] > rm -rf app/build && mkdirp app/build
[cleanup     ]
[icebear-copy]
[icebear-copy] > peerio-2@2.107.0 icebear-copy /root/peerio-desktop-2.107.0/package.json
[icebear-copy] > opt --in link-sdk --exec "./scripts/link_local_icebear.js"
[icebear-copy]
[icebear-copy]
[icebear-copy] > peerio-2@2.107.0 icebear-copy /root/peerio-desktop-2.107.0
[icebear-copy] > opt --in link-sdk --exec "./scripts/link_local_icebear.js"
[icebear-copy]
[compile:code    ]
[compile:code    ] > peerio-2@2.107.0 compile:code /root/peerio-desktop-2.107.0/package.json
[compile:code    ] > babel --source-maps -q src -d app/build --ignore emojione.js
[compile:code    ]
[compile:icebear ]
[compile:icebear ] > peerio-2@2.107.0 compile:icebear /root/peerio-desktop-2.107.0/package.json
[compile:icebear ] > babel --source-maps -q app/node_modules/peerio-icebear/src -d app/node_modules/peerio-icebear/dist
[compile:icebear ]
[compile:style   ]
[compile:style   ] > peerio-2@2.107.0 compile:style /root/peerio-desktop-2.107.0/package.json
[compile:style   ] > node-sass src/styles/main.scss app/build/style.css
[compile:style   ]
[compile:devstyle]
[compile:devstyle] > peerio-2@2.107.0 compile:devstyle /root/peerio-desktop-2.107.0/package.json
[compile:devstyle] > node-sass src/ui/dev-tools/dev-tools-style.scss app/build/dev-tools-style.css
[compile:devstyle]
[static:copy     ]
[static:copy     ] > peerio-2@2.107.0 static:copy /root/peerio-desktop-2.107.0/package.json
[static:copy     ] > cp -f src/*.html app/build/ && cp -R src/static app/build
[static:copy     ]
[react-toolbox   ]
[react-toolbox   ] > peerio-2@2.107.0 react-toolbox /root/peerio-desktop-2.107.0/package.json
[react-toolbox   ] > react-toolbox-themr
[react-toolbox   ]
[compile:style   ]
[compile:style   ] > peerio-2@2.107.0 compile:style /root/peerio-desktop-2.107.0
[compile:style   ] > node-sass src/styles/main.scss app/build/style.css
[compile:style   ]
[compile:icebear ]
[compile:icebear ] > peerio-2@2.107.0 compile:icebear /root/peerio-desktop-2.107.0
[compile:icebear ] > babel --source-maps -q app/node_modules/peerio-icebear/src -d app/node_modules/peerio-icebear/dist
[compile:icebear ]
[compile:code    ]
[compile:code    ] > peerio-2@2.107.0 compile:code /root/peerio-desktop-2.107.0
[compile:code    ] > babel --source-maps -q src -d app/build --ignore emojione.js
[compile:code    ]
[compile:devstyle]
[compile:devstyle] > peerio-2@2.107.0 compile:devstyle /root/peerio-desktop-2.107.0
[compile:devstyle] > node-sass src/ui/dev-tools/dev-tools-style.scss app/build/dev-tools-style.css
[compile:devstyle]
[static:copy     ]
[static:copy     ] > peerio-2@2.107.0 static:copy /root/peerio-desktop-2.107.0
[static:copy     ] > cp -f src/*.html app/build/ && cp -R src/static app/build
[static:copy     ]
[react-toolbox   ]
[react-toolbox   ] > peerio-2@2.107.0 react-toolbox /root/peerio-desktop-2.107.0
[react-toolbox   ] > react-toolbox-themr
[react-toolbox   ]
[compile:devstyle] Rendering Complete, saving .css file...
[compile:devstyle] Wrote CSS to /root/peerio-desktop-2.107.0/app/build/dev-tools-style.css
[compile:icebear ] app/node_modules/peerio-icebear/src doesn't exist
[compile:icebear ] npm ERR! code ELIFECYCLE
[compile:icebear ] npm ERR! errno 2
[compile:icebear ] npm ERR! peerio-2@2.107.0 compile:icebear: `babel --source-maps -q app/node_modules/peerio-icebear/src -d app/node_modules/peerio-icebear/dist`
[compile:icebear ] npm ERR! Exit status 2
[compile:icebear ] npm ERR!
[compile:icebear ] npm ERR! Failed at the peerio-2@2.107.0 compile:icebear script.
[compile:icebear ] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[compile:icebear ]
[compile:icebear ] npm ERR! A complete log of this run can be found in:
[compile:icebear ] npm ERR!     /root/.npm/_logs/2018-01-22T19_57_49_596Z-debug.log
ERROR: "compile:icebear" exited with 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peerio-2@2.107.0 compile: `run-s -ln cleanup icebear-copy && run-p -ln compile:* static:copy react-toolbox`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peerio-2@2.107.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-22T19_57_49_713Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peerio-2@2.107.0 internal-build-linux: `NODE_ENV=production npm run compile && NODE_ENV=production build --linux --x64 --publish never`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peerio-2@2.107.0 internal-build-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-22T19_57_49_729Z-debug.log
`

**Comment by dchest** [comment]
Hello,

It seems like `peerio-icebear` dependency failed to install for some reason. Please try the following:

```
rm -rf node_modules
npm install
cd app
rm -rf node_modules
npm install
cd ..
```

Before you do that, there's another thing that needs to be done that was added recently and thus isn't mentioned in the documentation: in `app/package.json` change the value of `"socketServerUrl"` from `""` to `"wss://icebear.peerio.com"`.

Please let us know if this works.
Thanks!

**Comment by gkua** [comment]
Hi, thank you for your kind reply!
It *almost* worked, when i try to build for windows on my ubuntu 16 server, it still gets some kind of errors, i'm listing them below.
`
root@ubuntu-s-1vcpu-2gb-lon1-01:~/peerio-desktop-2.107.0# npm run internal-build
> peerio-2@2.107.0 internal-build /root/peerio-desktop-2.107.0
> NODE_ENV=production npm run compile && NODE_ENV=production build --mac --windows --x64 --publish never


> peerio-2@2.107.0 compile /root/peerio-desktop-2.107.0
> run-s -ln cleanup icebear-copy && run-p -ln compile:* static:copy react-toolbox

[cleanup     ]
[cleanup     ] > peerio-2@2.107.0 cleanup /root/peerio-desktop-2.107.0/package.json
[cleanup     ] > rm -rf app/build && mkdirp app/build
[cleanup     ]
[cleanup     ]
[cleanup     ] > peerio-2@2.107.0 cleanup /root/peerio-desktop-2.107.0
[cleanup     ] > rm -rf app/build && mkdirp app/build
[cleanup     ]
[icebear-copy]
[icebear-copy] > peerio-2@2.107.0 icebear-copy /root/peerio-desktop-2.107.0/package.json
[icebear-copy] > opt --in link-sdk --exec "./scripts/link_local_icebear.js"
[icebear-copy]
[icebear-copy]
[icebear-copy] > peerio-2@2.107.0 icebear-copy /root/peerio-desktop-2.107.0
[icebear-copy] > opt --in link-sdk --exec "./scripts/link_local_icebear.js"
[icebear-copy]
[compile:code    ]
[compile:code    ] > peerio-2@2.107.0 compile:code /root/peerio-desktop-2.107.0/package.json
[compile:code    ] > babel --source-maps -q src -d app/build --ignore emojione.js
[compile:code    ]
[compile:icebear ]
[compile:icebear ] > peerio-2@2.107.0 compile:icebear /root/peerio-desktop-2.107.0/package.json
[compile:icebear ] > babel --source-maps -q app/node_modules/peerio-icebear/src -d app/node_modules/peerio-icebear/dist
[compile:icebear ]
[compile:style   ]
[compile:style   ] > peerio-2@2.107.0 compile:style /root/peerio-desktop-2.107.0/package.json
[compile:style   ] > node-sass src/styles/main.scss app/build/style.css
[compile:style   ]
[compile:devstyle]
[compile:devstyle] > peerio-2@2.107.0 compile:devstyle /root/peerio-desktop-2.107.0/package.json
[compile:devstyle] > node-sass src/ui/dev-tools/dev-tools-style.scss app/build/dev-tools-style.css
[compile:devstyle]
[static:copy     ]
[static:copy     ] > peerio-2@2.107.0 static:copy /root/peerio-desktop-2.107.0/package.json
[static:copy     ] > cp -f src/*.html app/build/ && cp -R src/static app/build
[static:copy     ]
[react-toolbox   ]
[react-toolbox   ] > peerio-2@2.107.0 react-toolbox /root/peerio-desktop-2.107.0/package.json
[react-toolbox   ] > react-toolbox-themr
[react-toolbox   ]
[compile:code    ]
[compile:code    ] > peerio-2@2.107.0 compile:code /root/peerio-desktop-2.107.0
[compile:code    ] > babel --source-maps -q src -d app/build --ignore emojione.js
[compile:code    ]
[compile:style   ]
[compile:style   ] > peerio-2@2.107.0 compile:style /root/peerio-desktop-2.107.0
[compile:style   ] > node-sass src/styles/main.scss app/build/style.css
[compile:style   ]
[compile:icebear ]
[compile:icebear ] > peerio-2@2.107.0 compile:icebear /root/peerio-desktop-2.107.0
[compile:icebear ] > babel --source-maps -q app/node_modules/peerio-icebear/src -d app/node_modules/peerio-icebear/dist
[compile:icebear ]
[compile:devstyle]
[compile:devstyle] > peerio-2@2.107.0 compile:devstyle /root/peerio-desktop-2.107.0
[compile:devstyle] > node-sass src/ui/dev-tools/dev-tools-style.scss app/build/dev-tools-style.css
[compile:devstyle]
[static:copy     ]
[static:copy     ] > peerio-2@2.107.0 static:copy /root/peerio-desktop-2.107.0
[static:copy     ] > cp -f src/*.html app/build/ && cp -R src/static app/build
[static:copy     ]
[react-toolbox   ]
[react-toolbox   ] > peerio-2@2.107.0 react-toolbox /root/peerio-desktop-2.107.0
[react-toolbox   ] > react-toolbox-themr
[react-toolbox   ]
[compile:devstyle] Rendering Complete, saving .css file...
[compile:devstyle] Wrote CSS to /root/peerio-desktop-2.107.0/app/build/dev-tools-style.css
[compile:style   ] Rendering Complete, saving .css file...
[compile:style   ] Wrote CSS to /root/peerio-desktop-2.107.0/app/build/style.css
electron-builder 0.0.0-semantic-release
Rebuilding native production dependencies for darwin:x64
Packaging for darwin x64 using electron 1.7.10 to dist/mac
Downloading tmp-9198-0-electron-v1.7.10-darwin-x64.zip
[============================================>] 100.0% of 48.42 MB (1.34 MB/s)
⚠️  macOS application code signing is supported only on macOS, skipping.
Building macOS zip
Building DMG
Downloading tmp-9198-1-electron-v1.7.10-win32-x64.zip
[============================================>] 100.0% of 53.89 MB (7.43 MB/s)
Downloading winCodeSign-1.9.0, please wait
Error: Cannot check wine version: Error: Exit code: ENOENT. spawn wine ENOENT
    at /root/peerio-desktop-2.107.0/node_modules/builder-util/src/wine.ts:82:13
    at Generator.throw (<anonymous>)
From previous event:
    at checkWineVersion (/root/peerio-desktop-2.107.0/node_modules/builder-util/out/wine.js:50:22)
    at Lazy.<anonymous> (/root/peerio-desktop-2.107.0/node_modules/builder-util/src/wine.ts:44:9)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (/root/peerio-desktop-2.107.0/node_modules/lazy-val/src/main.ts:18:23)
    at execWine (/root/peerio-desktop-2.107.0/node_modules/builder-util/src/wine.ts:54:27)
    at /root/peerio-desktop-2.107.0/node_modules/electron-builder/src/winPackager.ts:337:11
From previous event:
    at WinPackager.signAndEditResources (/root/peerio-desktop-2.107.0/node_modules/electron-builder/out/winPackager.js:447:11)
    at WinPackager.signApp (/root/peerio-desktop-2.107.0/node_modules/electron-builder/src/winPackager.ts:353:17)
    at /root/peerio-desktop-2.107.0/node_modules/electron-builder/src/platformPackager.ts:209:16
From previous event:
    at WinPackager.doPack (/root/peerio-desktop-2.107.0/node_modules/electron-builder/out/platformPackager.js:267:11)
    at /root/peerio-desktop-2.107.0/node_modules/electron-builder/src/platformPackager.ts:115:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/root/peerio-desktop-2.107.0/node_modules/electron-builder/out/platformPackager.js:190:11)
    at /root/peerio-desktop-2.107.0/node_modules/electron-builder/src/packager.ts:260:24
From previous event:
    at Packager.doBuild (/root/peerio-desktop-2.107.0/node_modules/electron-builder/out/packager.js:332:11)
    at /root/peerio-desktop-2.107.0/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/root/peerio-desktop-2.107.0/node_modules/electron-builder/out/packager.js:261:11)
    at /root/peerio-desktop-2.107.0/node_modules/electron-builder/src/builder.ts:283:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/root/peerio-desktop-2.107.0/node_modules/electron-builder/out/builder.js:63:21)
    at then (/root/peerio-desktop-2.107.0/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/root/peerio-desktop-2.107.0/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/root/peerio-desktop-2.107.0/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/root/peerio-desktop-2.107.0/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/root/peerio-desktop-2.107.0/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/root/peerio-desktop-2.107.0/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! peerio-2@2.107.0 internal-build: `NODE_ENV=production npm run compile && NODE_ENV=production build --mac --windows --x64 --publish never`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the peerio-2@2.107.0 internal-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by dchest** [comment]
Looks like it misses Wine. The dependencies needed to build for Windows on Linux are described here: https://www.electron.build/multi-platform-build (see "To build app for Windows on Linux" section). I think you don't need Mono, since we use NSIS installer.

(BTW, we build on macOS, so we don't test cross-platform builds on Linux, but I think it should work apart from code signing for macOS.)

**Comment by gkua** [comment]
I'm back once again..
I installed wine, skipped mono since you said it wasn't needed.
```
Building nsis installer (x64 and ia32)
Error: spawn hdiutil ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at spawn (/root/peerio-desktop-2.107.0/node_modules/builder-util/src/util.ts:190:3)
    at /root/peerio-desktop-2.107.0/node_modules/electron-builder/src/targets/dmg.ts:226:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at createStageDmg (/root/peerio-desktop-2.107.0/node_modules/electron-builder/out/targets/dmg.js:30:21)
    at /root/peerio-desktop-2.107.0/node_modules/electron-builder/src/targets/dmg.ts:30:27
    at Generator.next (<anonymous>)
    at LOOP (fs.js:1745:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at DmgTarget.build (/root/peerio-desktop-2.107.0/node_modules/electron-builder/out/targets/dmg.js:247:11)
    at taskManager.addTask.default.map.it (/root/peerio-desktop-2.107.0/node_modules/electron-builder/src/platformPackager.ts:120:85)
From previous event:
    at MacPackager.packageInDistributableFormat (/root/peerio-desktop-2.107.0/node_modules/electron-builder/src/platformPackager.ts:120:41)
    at /root/peerio-desktop-2.107.0/node_modules/electron-builder/src/macPackager.ts:89:26
From previous event:
    at /root/peerio-desktop-2.107.0/node_modules/electron-builder/src/macPackager.ts:89:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/root/peerio-desktop-2.107.0/node_modules/electron-builder/out/macPackager.js:183:11)
    at /root/peerio-desktop-2.107.0/node_modules/electron-builder/src/packager.ts:260:24
From previous event:
    at Packager.doBuild (/root/peerio-desktop-2.107.0/node_modules/electron-builder/out/packager.js:332:11)
    at /root/peerio-desktop-2.107.0/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/root/peerio-desktop-2.107.0/node_modules/electron-builder/out/packager.js:261:11)
    at /root/peerio-desktop-2.107.0/node_modules/electron-builder/src/builder.ts:283:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/root/peerio-desktop-2.107.0/node_modules/electron-builder/out/builder.js:63:21)
    at then (/root/peerio-desktop-2.107.0/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/root/peerio-desktop-2.107.0/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/root/peerio-desktop-2.107.0/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/root/peerio-desktop-2.107.0/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/root/peerio-desktop-2.107.0/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/root/peerio-desktop-2.107.0/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! peerio-2@2.107.0 internal-build: `NODE_ENV=production npm run compile && NODE_ENV=production build --mac --windows --x64 --publish never`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the peerio-2@2.107.0 internal-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by dchest** [comment]
Ah, right, you can't build DMG image for macOS on Linux, since it doesn't have `hdiutil`. 

If you just want the Windows version, please try this command:

```
NODE_ENV=production npm run compile && NODE_ENV=production ./node_modules/.bin/build --windows --publish never
```

I'll add it as `npm run internal-build-win` in the future version.

**Comment by gkua** [comment]
That works like a charm, thank you!
How to link icebear sdk? Do i use npm link? I couldn't find any information regarding that, sorry if i'm mistaken.

**Comment by anri-asaturov** [comment]
1. In the icebear repository folder run `npm link` once to create global link.
2. In the desktop repository folder create file named `.opt-in` and put this text in it: `link-sdk`

From now on all dev lifecycle commands and scripts will automatically use your local icebear repository (will copy it into node_modules whenever needed, also will watch icebear sdk folder for changes).

Just curious if could you share your intentions working with the Peerio sources?

**Comment by flohdot** [comment]
PS more info on opt-ins here: https://github.com/PeerioTechnologies/peerio-desktop/blob/dev/docs/development.md (but you should only need to do any of this if you're planning to work with the sources in development mode)

**Comment by gkua** [comment]
Thanks for the reply both, I would gladly discuss my intentions with peerio via email.

**Comment by anri-asaturov** [comment]
@gkua via Peerio, you wanted to say? ;)

**Comment by gkua** [comment]
My mistake, sorry. 
I messaged on Peerio. :)
